#
# General settings
#

debug: false # Send debug messages to console

#
# Currency settings
#

currency:
  name:
    singular: Dollar
    plural: Dollars
  symbol: $
  remove-drops: true # Prevent valuable items from dropping when killing mobs
  value: # https://jd.papermc.io/paper/1.21/org/bukkit/Material.html
    GOLD_INGOT: 1
    GOLD_BLOCK: 9

#
# Auto save settings
#

auto-save:
  enabled: true
  frequency: 900 # Frequency in seconds (900 seconds = every 15 minutes)

update-tracker:
  enabled: true
  frequency: 900 # Frequency in seconds (900 seconds = every 15 minutes)

commands:
  balance:
    enabled: true # Disabling this will prevent users with permission 'banco.user' from using /balance
  pay:
    enabled: true # Disabling this will prevent users with permission 'banco.user' from using /pay